#!/bin/bash
set -euxo pipefail

echo "Checking if all of the lab questions have been answered."

if /opt/workshops/instruqt-ctfd.sh --check;
then
    echo "All of the labs have been completed!"
else
    fail-message "Please complete all of the lab questions before moving on."
fi