slug: security-od-event-query-language-data-exploration
developers:
  - james.murray@elastic.co
  - douglas.sentz@elastic.co
  - karina.compton@elastic.co
  - nicholas.mezhir@elastic.co
elastic-stack:
  current-version: 8.18.2
  versions-allowed:
    - 8.18.2
content-scope:
  description: In this track you will learn what the Event Query Language (EQL) is, the syntax, and use cases. This track is meant for Security personnel looking to find chains of events in their Elastic logs.
  prerequisites: 'Intro to Elastic Security Path. Detection Engine Basics.'
learning-objective:
  track: Use the Event Query Language (EQL) to find a chain of events in Elastic logs with Timelines and create a detection rule to automate finding this chain of events.
  lo1: Explain the purpose, use cases, and syntax of EQL in order to craft security-focused queries.
  lo2: Build an EQL query in Timelines to identify network traffic events.
  lo3: Craft an EQL query in Timelines to identify host-based events.
  lo4: Construct an EQL query in Timelines to correlate different data sources (host vs network) as part of a single event.
  lo5: Create an EQL detection rule to automate detections.
target-audience:
  notes: 'Security Personnel'
our-named-tags:
  module-name: event-query-language-data-exploration
  status: ready-for-production
  content-type: od
  module-version: 1.0.2
  solution: security
  elastic-version: 8.18.2
  category-name: intermediate
  team: curriculum
instruqt-tags:
  - status/production
  - team/curriculum
  - category-name/intermediate
  - module-version/1.0.2
  - content-type/od
  - elastic-version/8.18.2
  - module-name/event-query-language-data-exploration
  - solution/security
